### ISSUE TITLE
Table and Rectangles?

### ISSUE THREAD

**Issue by vineethvijayan** [nRewik/SimplePDF#1]
is it possible to create table and rectangles like below??

![reportjpg_pdf__page_2_of_8_](https://cloud.githubusercontent.com/assets/6049347/12720145/3534810e-c91f-11e5-9d52-d945ccd0e74a.png)
![reportjpg_pdf__page_5_of_8_](https://cloud.githubusercontent.com/assets/6049347/12720146/353705e6-c91f-11e5-8dfb-b998a351574f.png)

**Comment by nRewik** [comment]
No, currently it can't create a table, or drawing anything except texts and images.

**Comment by vineethvijayan** [comment]
thanks closing this issue
