### ISSUE TITLE
Table extensions

### ISSUE THREAD

**Issue by mrichtsfeld** [nRewik/SimplePDF#10]
Hi, first of all, great library. 

I'm working a lot with tables and would like to make some extensions there. 
First the content alignment is not taken into account for table which means text is always centered. 
Second it would be great to pass attributed text to a table which give great flexibility in displaying. 

If you don't mind I will implement this and create a PR?

**Comment by caloon** [comment]
Another issue I'm having with tables is that there's no carriage return / multi-line support. If the text is too long, it simply gets drawn outside the cell's frame.

**Comment by mrichtsfeld** [comment]
@caloon I also already stumbled over this issue and would need it fixed. I will add it to my changes.

**Comment by caloon** [comment]
What is the status on this? Are you still planning to create a PR for tables?

**Comment by mrichtsfeld** [comment]
@caloon yes apart from the multiline support everything is finished so far, I only need to cleanup. I hope I can create a PR next week.

**Comment by hemangshah** [comment]
@mrichtsfeld – Have you added the PR? @nRewik – Have you adopted his PR?

**Comment by mrichtsfeld** [comment]
@hemangshah - I did not add it yet. Will do and let you know.

**Comment by mrichtsfeld** [comment]
@hemangshah, @nRewik - I have create a pull request with my changes, please tell me if anything is unclear or needs to be adapted. https://github.com/nRewik/SimplePDF/pull/14

**Comment by nRewik** [comment]
Merged with the new release.
