### ISSUE TITLE
Podspec platform

### ISSUE THREAD

**Issue by jaceee** [nRewik/SimplePDF#2]
I am currently working on a project with a minimum platform target of iOS 8.0 and need to generate a PDF. I found this library and tried to install it via cocoapods and found that i was unable to do so because of the platform in your podspec is `:ios, "9.0"`.

So, I just tried to add the file `SimplePDF.swift` to the project and use it and found **I was able to compile and use your library without problems**.

Could you set your podspec's platform to `:ios, "8.0"``?

**Comment by nRewik** [comment]
Sure, I will update it to 8.0 😀.

**Comment by jaceee** [comment]
That was fast! :open_mouth:
Thanks a lot.
