### ISSUE TITLE
Issue with compile errors

### ISSUE THREAD

**Issue by f15radar** [nRewik/SimplePDF#23]
I added this to my project, but I m getting compile errors in SimplePDF.swift => drawtext

        let attributes: [NSAttributedStringKey: Any] = [
            .font: font,
            .foregroundColor: textColor,
            .paragraphStyle: paragraphStyle
        ]

Type 'NSString' has no member 'font'

        let attributes: [NSAttributedStringKey: Any] = [
            .foregroundColor: textColor,
            .paragraphStyle: paraStyle,
            .obliqueness: skew,
            .font: font
        ]

Type 'NSString' has no member 'foregroundColor'

Any clues?

**Comment by nRewik** [comment]
What’s Swift version that you use ?

**Comment by f15radar** [comment]
Sorry....3.2, I guess I need to update to 4 or do you have a 3 version?

**Comment by nRewik** [comment]
I think you can use version 3 from the previous release.

Nutchaphon Rewik
________________________________

**Comment by f15radar** [comment]
Now I am getting pdf does not have a member writeToFile.  I am using v2.0.0

**Comment by cogsdawgs** [comment]
when I use try? pdfData.write(to: path, options: .atomic) it gives me a URL error.  Any easy ways to get around that?
