### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by ComandanteBL** [nRewik/SimplePDF#4]
Hello, I was wondering is there any way to add table inside PDF?
I like your pod, good job!
Thanks in advance.

**Comment by nRewik** [comment]
Thank you. 👍

SimplePDF doesn't support adding table to PDF.

**Comment by martinpfannemueller** [comment]
I created a very simple table drawing function. It can definitely be improved, but maybe this is enough for you. See #5

**Comment by nRewik** [comment]
Now, SimplePDF supports adding simple tables with text. Thanks to @martinpfannemueller.
