### ISSUE TITLE
replacing +/-infinity with -2147483648

### ISSUE THREAD

**Issue by antonioreyna** [nRewik/SimplePDF#8]
Im getting that error on line 161 CTFrameDraw(frameRef, currentContext)

**Comment by TotemChris** [comment]
I'm getting the same thing.  After researching a bit, it looks like a bug in iOS 10.1, but is fixed in 10.2.  See this tweet:

https://twitter.com/steipete/status/764446752472698880

**Comment by nRewik** [comment]
Thanks, @RiverbayChris. Close this issue since it was fixed.
